#!/bin/bash
set -e

SYSTEMD_STATUS=$(systemctl is-system-running)

if [[ "$SYSTEMD_STATUS" == "offline" ]]; then
  echo "systemd status $SYSTEMD_STATUS"
else
  echo "Installing systemd cudo-miner service"
  systemctl --system daemon-reload
  systemctl enable "cudo-miner"

  echo "Starting cudo-miner service..."
  systemctl start "cudo-miner"
fi
